---
abstract: 'Allow for compile time traits application in classes/roles'
author:
  - 'Nicholas Perez <nperez@cpan.org>'
generated_by: 'Dist::Zilla version 1.092680'
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: MooseX-CompileTime-Traits
requires:
  MooseX::Declare: 0.31
  Test::More: 0.92
resources:
  repository: git://github.com/nperez/moosex-compiletime-traits.git
version: 0.092800
